spring.application.name=api-gateway
server.port=8080

# KV SERVICE ROUTE
spring.cloud.gateway.routes[0].id=kv-service-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/keys/**

spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=kvServiceCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/kv-service

# REPLICATION SERVICE ROUTE
spring.cloud.gateway.routes[1].id=replication-service-route
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/replicas/**,/api/v1/replication/**

# CLUSTER SERVICE ROUTE
spring.cloud.gateway.routes[2].id=cluster-service-route
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/cluster/**

# METRICS SERVICE ROUTE
spring.cloud.gateway.routes[3].id=metrics-service-route
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/metrics/**

# GLOBAL CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=[http://localhost:3001,http://localhost:5173](http://localhost:3001,http://localhost:5173)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# RESILIENCE4J
resilience4j.circuitbreaker.instances.kvServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.kvServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.kvServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.timelimiter.instances.kvServiceCircuitBreaker.timeoutDuration=4s

# ACTUATOR
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# LOGGING
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.filter.factory=TRACE
