spring.application.name=replication-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:postgresql://localhost:5433/replication_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.topics.kv-events=${KV_EVENTS_TOPIC:kv-events}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Add this to ALL services while not using Eureka
eureka.client.enabled=false

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true