spring.application.name=metrics-service


server.port=${SERVER_PORT:8084}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/metrics_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always

# Add this to ALL services while not using Eureka
eureka.client.enabled=false
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.topics.kv-events=${KV_EVENTS_TOPIC:kv-events}
app.kafka.topics.cluster-events=${CLUSTER_EVENTS_TOPIC:cluster-events}

app.cluster-service.url=${CLUSTER_SERVICE_URL:http://localhost:8083}
app.replication-service.url=${REPLICATION_SERVICE_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.distributed.kvstore=DEBUG
# Add this to ALL services while not using Eureka